[book]
title = "GLaDOS Language Documentation"
authors = ["GLaDOS Team"]
language = "en"
multilingual = false
src = "src"

[build]
build-dir = "book"
create-missing = true

[output.html]
default-theme = "light"
git-repository-url = "https://github.com/yourusername/glados"
